name: Build LLVM

on:
  workflow_dispatch:
  #release:
  #  types: [published]
jobs:
  windows_x86:
    runs-on: windows-latest

    steps:
    - name: Clone Qwerty repo
      uses: actions/checkout@v4
      with:
        repository: gt-tinker/qwerty
        ref: wip/debug-windows
    - name: Build LLVM
      working-directory: ci/build-windows
      run: |
        #if ($Env:GITHUB_REF.StartsWith('refs/tags/v')) {
        #    $llvm_version = $Env:GITHUB_REF.Substring('refs/tags/v'.Length)
        #} else {
        #    $llvm_version = $Env:GITHUB_REF
        #}

        #if (-not ($llvm_version -match '\d+\.\d+\.\d+')) {
        #    Write-Error "`$GITHUB_REF is not an LLVM version: $Env:GITHUB_REF"
        #    exit 1
        #}

        #if (Test-Path 'C:\qwerty\build-zipped-up\llvm') {
        #    rm -r 'C:\qwerty\build-zipped-up\llvm'
        #}
        #.\build-llvm.ps1 -version $llvm_version
        .\build-llvm.ps1 -version 20.1.7
    #- name: Release
    #  uses: softprops/action-gh-release@v1
    #  if: startsWith(github.ref, 'refs/tags/')
    #  with:
    #    # If the glob below doesn't match anything, don't silently fail
    #    fail_on_unmatched_files: true
    #    # Glob package used by softprops/action-gh-release says:
    #    # "Please only use forward-slashes in glob expressions."
    #    # https://www.npmjs.com/package/glob#windows
    #    files: |
    #      C:/qwerty/build-zipped-up/llvm/llvm_*.zip
